on: ["push", "pull_request"]

name: Test

jobs:
    linting:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.10"

        - name: Install Dependencies
          run: pip install .[lint]

        - name: Run Black
          run: black --check .

        - name: Run flake8
          run: flake8 .

        - name: Run isort
          run: isort --check-only .

    type-check:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.10"

        - name: Install Dependencies
          run: pip install .[lint,test]  # Might need test deps

        - name: Run MyPy
          run: mypy .

    functional:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]   # eventually add `windows-latest`
                python-version: ["3.9", "3.10", "3.11", "3.12"]

        steps:
        - uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
              python-version: ${{ matrix.python-version }}

        - name: Install Dependencies
          run: pip install .[test]

        - name: Run Tests
          run: ape test -s
